--
-- PostgreSQL database dump
--

\restrict GC1diirdMcKae4zDuVw3D3VwsYig1t7M8kbMVBjTDMMm3syYEBOhD6mhFWN1agK

-- Dumped from database version 13.23 (Debian 13.23-1.pgdg13+1)
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-07 08:25:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;

--
-- TOC entry 3198 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 201 (class 1259 OID 17680)
-- Name: episodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.episodes (
    episode_number integer,
    season_number integer,
    id bigint NOT NULL,
    season_id bigint,
    overview text,
    still_path character varying(255),
    title character varying(255),
    video_url character varying(255)
);


--
-- TOC entry 200 (class 1259 OID 17678)
-- Name: episodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.episodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.episodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 17690)
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.favorites (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    mediacontent_id bigint,
    user_id bigint
);


--
-- TOC entry 202 (class 1259 OID 17688)
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 17695)
-- Name: genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.genres (
    id bigint NOT NULL,
    name character varying(255)
);


--
-- TOC entry 205 (class 1259 OID 17700)
-- Name: mediacontent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.mediacontent (
    is_deleted boolean DEFAULT false NOT NULL,
    popularity double precision,
    tmdb_vote double precision,
    vote_count integer,
    movie_id bigint NOT NULL,
    movie_lens_id bigint,
    release_date timestamp(6) without time zone,
    tmdb_id bigint,
    dtype character varying(31) NOT NULL,
    backdrop_path character varying(255),
    original_language character varying(255),
    original_title character varying(255),
    overview text,
    poster_path character varying(255),
    title character varying(255)
);


--
-- TOC entry 206 (class 1259 OID 17711)
-- Name: mediacontent_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.mediacontent_genres (
    genre_id bigint NOT NULL,
    mediacontent_id bigint NOT NULL
);


--
-- TOC entry 208 (class 1259 OID 17716)
-- Name: model_registry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.model_registry (
    f1_score double precision,
    id integer NOT NULL,
    is_active boolean,
    mae double precision,
    "precision" double precision,
    recall double precision,
    rmse double precision,
    version double precision,
    created_at timestamp(6) without time zone,
    job_id character varying(255),
    model_name character varying(255),
    model_path character varying(255)
);


--
-- TOC entry 207 (class 1259 OID 17714)
-- Name: model_registry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.model_registry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_registry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 17724)
-- Name: movies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.movies (
    movie_id bigint NOT NULL,
    runtime integer,
    trailer_key character varying(255)
);


--
-- TOC entry 211 (class 1259 OID 17731)
-- Name: ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.ratings (
    score double precision,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    mediacontent_id bigint,
    user_id bigint,
    comment character varying(255)
);


--
-- TOC entry 210 (class 1259 OID 17729)
-- Name: ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 17738)
-- Name: seasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.seasons (
    air_date date,
    season_number integer NOT NULL,
    id bigint NOT NULL,
    series_id bigint,
    name character varying(255)
);


--
-- TOC entry 212 (class 1259 OID 17736)
-- Name: seasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 17743)
-- Name: series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.series (
    movie_id bigint NOT NULL,
    status character varying(255)
);


--
-- TOC entry 215 (class 1259 OID 17748)
-- Name: training_jobs_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.training_jobs_logs (
    colleborating_time double precision,
    content_based_time double precision,
    created_at timestamp(6) without time zone,
    error_message text,
    id character varying(255) NOT NULL,
    job_status character varying(255)
);


--
-- TOC entry 216 (class 1259 OID 17756)
-- Name: user_preferred_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.user_preferred_genres (
    genre_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 17763)
-- Name: user_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.user_tokens (
    revoked boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255)
);


--
-- TOC entry 217 (class 1259 OID 17761)
-- Name: user_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17770)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.users (
    is_deleted boolean NOT NULL,
    id bigint NOT NULL,
    email character varying(255),
    full_name character varying(255),
    password character varying(255),
    role character varying(20) DEFAULT 'USER'::character varying,
    user_name character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- TOC entry 219 (class 1259 OID 17768)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17782)
-- Name: watch_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.watch_histories (
    id bigint NOT NULL,
    media_content_id bigint,
    user_id bigint,
    watched_at timestamp(6) without time zone
);


--
-- TOC entry 221 (class 1259 OID 17780)
-- Name: watch_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.watch_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watch_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3019 (class 2606 OID 17687)
-- Name: episodes episodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.episodes
    ADD CONSTRAINT episodes_pkey PRIMARY KEY (id);


--
-- TOC entry 3021 (class 2606 OID 17694)
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- TOC entry 3023 (class 2606 OID 17699)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 3025 (class 2606 OID 17708)
-- Name: mediacontent mediacontent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mediacontent
    ADD CONSTRAINT mediacontent_pkey PRIMARY KEY (movie_id);


--
-- TOC entry 3027 (class 2606 OID 17710)
-- Name: mediacontent mediacontent_tmdb_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mediacontent
    ADD CONSTRAINT mediacontent_tmdb_id_key UNIQUE (tmdb_id);


--
-- TOC entry 3029 (class 2606 OID 17723)
-- Name: model_registry model_registry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.model_registry
    ADD CONSTRAINT model_registry_pkey PRIMARY KEY (id);


--
-- TOC entry 3031 (class 2606 OID 17728)
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (movie_id);


--
-- TOC entry 3033 (class 2606 OID 17735)
-- Name: ratings ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT ratings_pkey PRIMARY KEY (id);


--
-- TOC entry 3035 (class 2606 OID 17742)
-- Name: seasons seasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT seasons_pkey PRIMARY KEY (id);


--
-- TOC entry 3037 (class 2606 OID 17747)
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (movie_id);


--
-- TOC entry 3039 (class 2606 OID 17755)
-- Name: training_jobs_logs training_jobs_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_jobs_logs
    ADD CONSTRAINT training_jobs_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 3041 (class 2606 OID 17760)
-- Name: user_preferred_genres user_preferred_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferred_genres
    ADD CONSTRAINT user_preferred_genres_pkey PRIMARY KEY (genre_id, user_id);


--
-- TOC entry 3043 (class 2606 OID 17767)
-- Name: user_tokens user_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tokens
    ADD CONSTRAINT user_tokens_pkey PRIMARY KEY (id);


--
-- TOC entry 3045 (class 2606 OID 17779)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3047 (class 2606 OID 17786)
-- Name: watch_histories watch_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_histories
    ADD CONSTRAINT watch_histories_pkey PRIMARY KEY (id);


--
-- TOC entry 3051 (class 2606 OID 17802)
-- Name: mediacontent_genres fk21tu0ylkm5jh5am1qbxe8bw9l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mediacontent_genres
    ADD CONSTRAINT fk21tu0ylkm5jh5am1qbxe8bw9l FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- TOC entry 3060 (class 2606 OID 17847)
-- Name: user_tokens fk61iiu6gfevpvo2v3yl76sar7r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tokens
    ADD CONSTRAINT fk61iiu6gfevpvo2v3yl76sar7r FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3048 (class 2606 OID 17787)
-- Name: episodes fk7ivf70l3s8bib2w4765nkhcak; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.episodes
    ADD CONSTRAINT fk7ivf70l3s8bib2w4765nkhcak FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- TOC entry 3061 (class 2606 OID 17852)
-- Name: watch_histories fkavts94q0qjpkb3h0qq2dheji4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_histories
    ADD CONSTRAINT fkavts94q0qjpkb3h0qq2dheji4 FOREIGN KEY (media_content_id) REFERENCES public.mediacontent(movie_id);


--
-- TOC entry 3054 (class 2606 OID 17822)
-- Name: ratings fkb3354ee2xxvdrbyq9f42jdayd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fkb3354ee2xxvdrbyq9f42jdayd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3056 (class 2606 OID 17827)
-- Name: seasons fkh1pirq6juf6a9jpsxjtfbam6x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT fkh1pirq6juf6a9jpsxjtfbam6x FOREIGN KEY (series_id) REFERENCES public.series(movie_id);


--
-- TOC entry 3055 (class 2606 OID 17817)
-- Name: ratings fkhaehu48gvsqyc5r1de6pxjct3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fkhaehu48gvsqyc5r1de6pxjct3 FOREIGN KEY (mediacontent_id) REFERENCES public.mediacontent(movie_id);


--
-- TOC entry 3058 (class 2606 OID 17842)
-- Name: user_preferred_genres fkin6otrf7tifbuhdhtiicm6g9n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferred_genres
    ADD CONSTRAINT fkin6otrf7tifbuhdhtiicm6g9n FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3049 (class 2606 OID 17797)
-- Name: favorites fkk7du8b8ewipawnnpg76d55fus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkk7du8b8ewipawnnpg76d55fus FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3062 (class 2606 OID 17857)
-- Name: watch_histories fkkkt9kxb5vsip9tr1djijfylg1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.watch_histories
    ADD CONSTRAINT fkkkt9kxb5vsip9tr1djijfylg1 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3057 (class 2606 OID 17832)
-- Name: series fkkpbgp674m4g5x4tm4kci7jbuc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT fkkpbgp674m4g5x4tm4kci7jbuc FOREIGN KEY (movie_id) REFERENCES public.mediacontent(movie_id);


--
-- TOC entry 3059 (class 2606 OID 17837)
-- Name: user_preferred_genres fkovxesnaxyo1tm3baxi2vccl18; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferred_genres
    ADD CONSTRAINT fkovxesnaxyo1tm3baxi2vccl18 FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- TOC entry 3052 (class 2606 OID 17807)
-- Name: mediacontent_genres fkpo2dklk8i26lme2svae6lmh1x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mediacontent_genres
    ADD CONSTRAINT fkpo2dklk8i26lme2svae6lmh1x FOREIGN KEY (mediacontent_id) REFERENCES public.mediacontent(movie_id);


--
-- TOC entry 3053 (class 2606 OID 17812)
-- Name: movies fkqkqkfsrqo3sutd0h6a6jmc3v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT fkqkqkfsrqo3sutd0h6a6jmc3v FOREIGN KEY (movie_id) REFERENCES public.mediacontent(movie_id);


--
-- TOC entry 3050 (class 2606 OID 17792)
-- Name: favorites fkqukdksd3ces6m2pov4tm2to7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT fkqukdksd3ces6m2pov4tm2to7m FOREIGN KEY (mediacontent_id) REFERENCES public.mediacontent(movie_id);


-- Completed on 2026-03-07 08:25:26

--
-- PostgreSQL database dump complete
--

\unrestrict GC1diirdMcKae4zDuVw3D3VwsYig1t7M8kbMVBjTDMMm3syYEBOhD6mhFWN1agK


COPY public.genres(id, name) 
FROM '/docker-entrypoint-initdb.d/extracted/genres_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.mediacontent(movie_id, tmdb_id, title, original_title, overview, release_date, poster_path, backdrop_path, tmdb_vote, vote_count, popularity, dtype, original_language) 
FROM '/docker-entrypoint-initdb.d/extracted/mediacontent_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.mediacontent_genres(mediacontent_id, genre_id) 
FROM '/docker-entrypoint-initdb.d/extracted/media_genres_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.series(movie_id,status) 
FROM '/docker-entrypoint-initdb.d/extracted/series_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.movies(movie_id, runtime ,trailer_key) 
FROM '/docker-entrypoint-initdb.d/extracted/movies_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.seasons(id, season_number,name, series_id) 
FROM '/docker-entrypoint-initdb.d/extracted/seasons_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');

COPY public.episodes(id, episode_number, title, overview, still_path, season_id) 
FROM '/docker-entrypoint-initdb.d/extracted/episodes_1.csv' 
WITH (FORMAT csv, HEADER true, DELIMITER ',', ENCODING 'UTF8');